name: lovingo
description: Application de rencontre moderne avec cadeaux virtuels et live streaming WebRTC
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.4.0'
  flutter: '>=3.19.0 <3.20.0'

dependencies:
  flutter:
    sdk: flutter

  # ✅ COMMUNICATION WEBRTC
  flutter_webrtc: ^0.11.7
  web_socket_channel: ^2.4.5

  # ✅ FIREBASE
  firebase_core: ^2.25.4
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  cloud_functions: ^4.7.6

  # ✅ PAIEMENT
  flutter_stripe: ^9.4.0

  # ✅ UI / ANIMATION
  lottie: ^2.7.0
  shimmer: ^3.0.0
  rive: ^0.11.4
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  confetti: ^0.7.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_staggered_animations: ^1.1.1

  # ✅ NAVIGATION
  go_router: ^10.1.2

  # ✅ ÉTAT GLOBAL
  riverpod: ^2.3.7
  flutter_riverpod: ^2.6.1

  # ✅ MÉDIA
  image_picker: ^1.0.2
  video_player: ^2.7.0
  camera: ^0.10.5+2
  photo_view: ^0.14.0

  # ✅ AUDIO
  audioplayers: ^6.0.0
  just_audio: ^0.9.34
  flutter_sound: ^9.28.0

  # ✅ GÉOLOCALISATION
  geolocator: ^10.1.1
  geocoding: ^2.1.0

  # ✅ PERMISSIONS
  permission_handler: ^11.3.1

  # ✅ STOCKAGE LOCAL
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # ✅ UTILITAIRES
  intl: ^0.18.1
  uuid: ^3.0.7
  dio: ^5.3.2
  http: ^1.1.0
  json_annotation: ^4.9.0

  # ✅ PARTAGE & SOCIAL
  share_plus: ^7.2.2
  url_launcher: ^6.2.2

  # ✅ NOTIFICATIONS
  flutter_local_notifications: ^17.2.3

  # ✅ ICÔNES
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

dependency_overrides:
  pigeon: ^17.1.2
  collection: 1.18.0
  meta: 1.9.0
  web: 0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
    - assets/fonts/
    - assets/icons/
    - assets/images/icons/
    - assets/images/avatars/
    - assets/images/gifts/
    - assets/images/backgrounds/
    - assets/data/
    - assets/sounds/incoming_call.mp3
    - assets/sounds/outgoing_call.mp3
    - assets/sounds/call_accept.mp3
    - assets/sounds/call_decline.mp3
    - assets/sounds/call_end.mp3
    - assets/sounds/button_tap.mp3
    - assets/sounds/notification.mp3
    - assets/sounds/new_message.mp3
    - assets/sounds/gift_received.mp3
    - assets/sounds/gift_sent.mp3
    - assets/sounds/live_start.mp3
    - assets/sounds/live_end.mp3
    - assets/sounds/user_joined.mp3
    - assets/sounds/user_left.mp3
    - assets/sounds/success.mp3
    - assets/sounds/error.mp3
    - assets/sounds/warning.mp3
    - assets/sounds/combo.mp3
    - assets/sounds/achievement.mp3
    - assets/animations/gift_heart.json
    - assets/animations/gift_diamond.json
    - assets/animations/gift_crown.json
    - assets/animations/gift_unicorn.json
    - assets/animations/gift_rainbow.json
    - assets/animations/live_streaming.json
    - assets/animations/call_connecting.json
    - assets/animations/loading.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: S
  main_locale: fr
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
