// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// `dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// `
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImoOBjHuV5i2CPDrc6Nszglzl1oisJ4M',
    appId: '1:351246394074:web:66ff77cf313e9d6076bbe3',
    messagingSenderId: '351246394074',
    projectId: 'lovingo-172839',
    authDomain: 'lovingo-172839.firebaseapp.com',
    storageBucket: 'lovingo-172839.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZFFABS4XONKKLkOFv-7CWPvfo4_ZA7XU',
    appId: '1:351246394074:android:bf5124b876b886e676bbe3',
    messagingSenderId: '351246394074',
    projectId: 'lovingo-172839',
    storageBucket: 'lovingo-172839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY8daWDEb9ZEKiSpEzFB7XnJi-6sxjnaQ',
    appId: '1:351246394074:ios:43d1bee9c45fc9a676bbe3',
    messagingSenderId: '351246394074',
    projectId: 'lovingo-172839',
    storageBucket: 'lovingo-172839.firebasestorage.app',
    iosBundleId: 'com.lovingo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY8daWDEb9ZEKiSpEzFB7XnJi-6sxjnaQ',
    appId: '1:351246394074:ios:43d1bee9c45fc9a676bbe3',
    messagingSenderId: '351246394074',
    projectId: 'lovingo-172839',
    storageBucket: 'lovingo-172839.firebasestorage.app',
    iosBundleId: 'com.lovingo.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAImoOBjHuV5i2CPDrc6Nszglzl1oisJ4M',
    appId: '1:351246394074:web:8b4e5bdf7ced5a6276bbe3',
    messagingSenderId: '351246394074',
    projectId: 'lovingo-172839',
    authDomain: 'lovingo-172839.firebaseapp.com',
    storageBucket: 'lovingo-172839.firebasestorage.app',
  );

}